=== franndonadio/Bryan-s-Coffee/branches.dtd
<!ELEMENT branches (branch+)>
<!ELEMENT branch (name, address, phone, email, latitude, longitude, hours, mapLink)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT hours (#PCDATA)>
<!ELEMENT mapLink (#PCDATA)>

=== franndonadio/Bryan-s-Coffee/branches.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE branches SYSTEM "branches.dtd">
<branches>
  <branch>
    <name>Sydney</name>
    <address>123 Pyrmont Street, Pyrmont, NSW 2009</address>
    <phone>+61 2 5555 5555</phone>
    <email>sydney@bryanscoffee.com.au</email>
    <latitude>-33.8688</latitude>
    <longitude>151.2093</longitude>
  </branch>
  <branch>
    <name>Melbourne</name>
    <address>456 Collins Street, Melbourne, VIC 3000</address>
    <phone>+61 3 5555 5555</phone>
    <email>melbourne@bryanscoffee.com.au</email>
    <latitude>-37.8136</latitude>
    <longitude>144.9631</longitude>
  </branch>
  <branch>
    <name>Brisbane</name>
    <address>789 Queen Street, Brisbane, QLD 4000</address>
    <phone>+61 7 5555 5555</phone>
    <email>brisbane@bryanscoffee.com.au</email>
    <latitude>-27.4698</latitude>
    <longitude>153.0251</longitude>
  </branch>
  <branch>
    <name>Airlie Beach</name>
    <address>101 Main Street, Airlie Beach, QLD 4802</address>
    <phone>+61 7 5555 5555</phone>
    <email>airlie@bryanscoffee.com.au</email>
    <latitude>-20.2679</latitude>
    <longitude>148.7166</longitude>
  </branch>
</branches>
